---
title: "Intro to Random Forests and its application on survival analysis"
output:
  pdf_document:
    toc: yes
  html_document:
    theme: united
    toc: yes
date: "03/01/2021"

---
### Random Forest on regression, THIS IS WHAT WE WANT TO DO FOR LOGSSD BECAUSE IT IS CONTINUOUS VARIABLE

```{r Hc20 example}
library(readxl)
library(dplyr)

data <- read_excel("Input_ALL_V01a.xlsx", sheet = "data")

data <- dplyr::filter(data, data$Count_nrd > 3)

data <- subset(data, select = c(MASS,
                                LD50_T,
ATM_O,
BIOC_O,
BIOD_O,
BP_O,
HL_O,
KM_O,
LOGKOA_O,
KOC_O,
LOGP_O,
MP_O,
VP_O,
WS_O,
LOG_M_LD50,
LOG_G_LD50,
LOG_LD50_25, logBMD25_nrd))

data1=data[1:1508,]
data =  na.omit(data)
#data =  na.omit(data)
set.seed(1)
idx = sample(1:nrow(data), nrow(data)*0.7)
train = data[idx,]
test = data[-idx,]
```

```{r ozone rf, warning=FALSE, message = FALSE}
library(randomForest)
set.seed(1)
comptoxBMD25.rf <- randomForest(logBMD25_nrd
 ~ MASS+LD50_T+ATM_O+BIOC_O+BIOD_O+BP_O+HL_O+KM_O+LOGKOA_O+KOC_O+LOGP_O+MP_O+VP_O+WS_O+LOG_M_LD50+LOG_G_LD50, data = train, 
 mtry = 3, ntree = 1000, importance = TRUE) 
comptoxBMD25.rf

#MASS+BIOC_T+BP_T+DAPHNIA_T+DEN_T+DEV_T+FATHEAD_T+FP_T+MP_T+AM_T+LD50_T+ST_T+TC_T+TETRA_T+VISC_T+VP_T+WS_T+ATM_O+BIOC_O+BIOD_O+BP_O+HL_O+KM_O+LOGKOA_O+KOC_O+LOGP_O+MP_O+VP_O+WS_

```

```{r tree size, echo=FALSE}
plot(comptoxBMD25.rf) 
#importance(comptoxBMD25.rf, class=NULL)
varImpPlot(comptoxBMD25.rf, n.var=12)

```
```{r rf regression prediction}
comptoxBMD25.predict.rf = predict(comptoxBMD25.rf, test[,-17])
# head(comptoxBMD25.rf)
require(MLmetrics)
names(comptoxBMD25.predict.rf) <- NULL
R2_Score(comptoxBMD25.predict.rf, test$logBMD25_nrd)

a <-plot(test$logBMD25_nrd, comptoxBMD25.predict.rf)+
abline(0,1)


b <-plot(comptoxBMD25.predict.rf, test$logBMD25_nrd)+
abline(0,1)

comptoxBMD25.predict.rf.total = predict(comptoxBMD25.rf, data1)
output.rf = cbind(data1, comptoxBMD25.predict.rf.total)

#write.csv(output.rf,"/Users/marysesuppiger/RFoutputOPERAandtestALL.csv", row.names = FALSE)

comptoxHC20 = predict(comptoxHC20.rf, data1)

```

## cross-validation for RF

```{r data preprocessing to create folds, warning=FALSE, message = FALSE}
set.seed(1)
folds <- split(sample(nrow(train), nrow(train), replace = FALSE), as.factor(1:10))
```

```{r find best parameters, warning=FALSE, message = FALSE}
#library(randomForest) this package cannot handle categorical variables with more than 53 levels
library(ranger)
library(caret)

mtry.list <- c(2, 5, 7, 10, 12) #10, 20, 30, 53
ntree.list <- c(100, 500, 1000)
R2.list <- vector()

for (i in mtry.list){
  for (j in ntree.list){
    R2_average <- 0
    for (k in 1:10){
      set.seed(1)
      BMD25_rf <- ranger(logBMD25_nrd
 ~ ATM_O + BIOC_O + BIOD_O + BP_O + HL_O + KM_O + LOGKOA_O + KOC_O + LOGP_O + MP_O + VP_O + WS_O, mtry=i, num.trees=j,
                   data = train[-folds[[k]], ])
      BMD25_predict_rf <- predict( BMD25_rf, train[folds[[k]], ])
      R2_average <- R2_average+R2_Score(BMD25_predict_rf$predictions, train[folds[[k]], ]$logBMD25_nrd)
    }
    performance <- c(i, j, R2_average/10)
    R2.list <- rbind(R2.list, performance)
  }
}
colnames(R2.list) <- c('mtry', 'ntree', 'R2')
R2.list
```

```{r randomForest function, warning=FALSE, message = FALSE}
require(caret)
cv_performance <- vector()
for (i in 1:10){
  set.seed(1)
  BMD25_rf <- ranger(logBMD25_nrd
 ~ ATM_O + BIOC_O + BIOD_O + BP_O + HL_O + KM_O + LOGKOA_O + KOC_O + LOGP_O + MP_O + VP_O + WS_O, mtry=7, num.trees=1000,
                 data = train[-folds[[i]], ])
  BMD25_predict_rf <- predict(BMD25_rf , train[folds[[i]], ])
  cv_performance <- c(cv_performance, R2_Score(BMD25_predict_rf$predictions, train[folds[[i]], ]$logBMD25_nrd))
}
cv_performance
mean(cv_performance)
```


```

